const CACHE='frombos-v2-2026-09-14-16';
const CORE=['./','./index.html','./manifest.webmanifest','./assets/css/app.css','./assets/css/features.css','./assets/css/champions.css','./assets/css/performance.css','./assets/css/competitive.css','./assets/css/meta.css','./assets/css/visual-polish.css','./assets/css/reports.css','./assets/css/open-series-observed.css','./assets/css/scouting-registry.css','./assets/css/vod-review.css','./assets/css/tactical-share.css','./assets/css/scouting-results.css','./assets/css/champion-visual-upgrade.css','./assets/js/app.js','./assets/js/data.js','./assets/js/store.js','./assets/js/draft-room.js','./assets/js/tactical.js','./assets/js/vod-review.js','./assets/js/champion-intelligence.js','./assets/js/champion-registry.generated.js','./assets/js/curated-champion-data.js','./assets/js/open-series-champions.generated.js','./assets/js/open-series-observed-ui.js','./assets/js/open-series-scouting.generated.js','./assets/js/scouting-registry-ui.js','./assets/js/open-series-results.generated.js','./assets/js/scouting-results-ui.js','./assets/js/performance-center.js','./assets/js/competitive-intelligence.js','./assets/js/competitive-router.js','./assets/js/meta-intelligence.js','./assets/js/meta-router.js','./assets/js/reports.js','./assets/js/reports-router.js','./assets/js/visual-polish.js','./assets/js/tactical-share-restore.js','./assets/js/champion-visual-upgrade.js'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==location.origin)return;
  const fresh=event.request.mode==='navigate'||/\.(?:js|css)$/.test(url.pathname);
  if(fresh){event.respondWith(fetch(event.request).then(resp=>{const copy=resp.clone();caches.open(CACHE).then(c=>c.put(event.request,copy));return resp;}).catch(()=>caches.match(event.request).then(hit=>hit||caches.match('./index.html'))));return;}
  event.respondWith(caches.match(event.request).then(hit=>hit||fetch(event.request).then(resp=>{const copy=resp.clone();caches.open(CACHE).then(c=>c.put(event.request,copy));return resp;}).catch(()=>caches.match('./index.html'))));
});
